### ISSUE TITLE
[Synchronization] **Sync Get block always**

### ISSUE THREAD

**Issue by Mrschengen** [nervosnetwork/neuron#2462]
### Detail of the issue

Hello team ! am asking if thers a solution to get out the funds from the DAO ! am not looking for more solution to keep minting the blocks ! if thers a solution to get out my funds i will appreciat it ! am really disapointed by Neuron wallet !  so if please can i get my funds out without waiting more the blocks to get syncing i will appreciat the help

**Comment by Keith-CY** [comment]
Hi @Mrschengen 

I thought the problem was solved because the issue was closed https://github.com/nervosnetwork/neuron/issues/2458#issuecomment-1200595791

As the last comment said, starting a ckb node manually could help, in fixing the problem of synchronization or getting a full log of the case

**Comment by Mrschengen** [comment]
The problem was not solved , and i didnt closed the issue ! Please now am asking if thers a solution to get out the funds from the dao ?

**Comment by Keith-CY** [comment]
> The problem was not solved , and i didnt closed the issue ! Please now am asking if thers a solution to get out the funds from the dao ?

The log in #2458 showed the `ckb node` inside `neuron` didn't work properly but the underlying reason was not clear because log didn't unveil it.

So we thought running a `ckb node` outside `neuron` may help.

1. If the `ckb node` outside `neuron` works properly, neuron should sync and you can get your fund out
2. If the `ckb node` outside `neuron` doesn't work properly, the full log(without unrelated info) can be used to locate the error.

Steps to run a `ckb node` outside `neuron` was elaborated in #2458

**Comment by Mrschengen** [comment]
i did that in one point get blocked also i was watching on CMD ! i will repeat again All even i dont have more patient for this ! can you imagine losing time and energy since 10 May on this ? ! anyway , will repeat and start all from zero again then lets see .
1) should i put CKB RUN and wait all the blocks or 
2) use that strategy >> ckb run --assume-valid-target 0x4e53fcf61c1250249bc201101bcc8c904b7fcd455f8db395bdb4bbe02502a499

**Comment by Keith-CY** [comment]
> 2\. ckb run --assume-valid-target 0x4e53fcf61c1250249bc201101bcc8c904b7fcd455f8db395bdb4bbe02502a499

`ckb run --assume-valid-target 0x4e53fcf61c1250249bc201101bcc8c904b7fcd455f8db395bdb4bbe02502a499` is speedy because it skips verifying blocks before https://explorer.nervos.org/block/0x4e53fcf61c1250249bc201101bcc8c904b7fcd455f8db395bdb4bbe02502a499

**Comment by Mrschengen** [comment]
am affraid that cant work, because i delet the cash yesterday when it get block again so i started all from zero but get block at 1,411,023/. 
so do you think if i  "  clear cash full rebuild"  this speedy trick will work ? or should in this point just run the CKB and wait all blocks from zero as no data on mainet !

**Comment by Keith-CY** [comment]
> am affraid that cant work, because i delet the cash yesterday when it get block again so i started all from zero but get block at 1,411,023/. so do you think if i " clear cash full rebuild" this speedy trick will work ? or should in this point just run the CKB and wait all blocks from zero as no data on mainet !

For now, just running the `ckb node` without running `neuron` is a good choice

Previously, `neuron` didn't work because `ckb node` inside it didn't work. Now we just run a `ckb node` outside it and to see if it can synchronize successfully.

If `ckb node` outside neuron reaches the latest block, then we can open neuron and clear cache.
If` ckb node` outside neuron doesn't work too, we should find out the reason from the full log of `ckb node`

**Comment by Mrschengen** [comment]
ok i will test that again :(

**Comment by Mrschengen** [comment]
![ckbversion](https://user-images.githubusercontent.com/109836736/182759015-6cf96c1a-a337-4fb9-99ea-4a0eee19aec7.png)
 i have checked the version in CMD and i dont get the same Version ( check image ) ! this can lead to the problem ? or no problem if i get result like that ?

**Comment by Keith-CY** [comment]
> ![ckbversion](https://user-images.githubusercontent.com/109836736/182759015-6cf96c1a-a337-4fb9-99ea-4a0eee19aec7.png) i have checked the version in CMD and i dont get the same Version ( check image ) ! this can lead to the problem ? or no problem if i get result like that ?

My fault, the one inside neuron is https://github.com/nervosnetwork/ckb/releases/tag/v0.103.0

**Comment by Keith-CY** [comment]
But you can keep using 0.104.0 if just want to get fund out

**Comment by Mrschengen** [comment]
please another question , i left the ckb node outside neuron working from yesterday ! didnt finish yet but until now its working fine ! am on on block 7480000, My question is;
 if i stoped using Ctrl+C and run the node later, this can not drain the node or create a problem?
in other mean if i restart my laptop this can creat a problem ? or it's necessary not stoping the node and keep the laptop working 24/24h

**Comment by Keith-CY** [comment]
> please another question , i left the ckb node outside neuron working from yesterday ! didnt finish yet but until now its working fine ! am on on block 4790000, My question is; if i stoped using Ctrl+C and run the node later, this can not drain the node or create a problem? in other mean if i restart my laptop this can creat a problem ? or it's necessary not stoping the node and keep the laptop working 24/24h

In most cases, it continues to work.
In some cases, it will be blocked by a `LOCK` file at `data\db\LOCK`, deleting it then restart node works
In rare cases, data will be broken and have to start from 0, it happens in early stage but now I haven't seen it.

**Comment by Mrschengen** [comment]
Hello, Finnaly the syncin goutside neuron reaches the latest block.
whats the next step now ? i need to open Neuron wallet now ? or how it work after if i want to withdraw for exemple from the dao ? 
![ckb node](https://user-images.githubusercontent.com/109836736/183305776-214ebc0f-ace1-40f3-aa8b-dd64c720d18b.png)

**Comment by Keith-CY** [comment]
> Hello, Finnaly the syncin outside neuron reaches the latest block. -whats the next step now ? i need to open Neuron wallet now ? -should i stop now the node outside and start neuron ? or how it work after if i want to withdraw for exemple from the dao ? ![ckb node](https://user-images.githubusercontent.com/109836736/183305776-214ebc0f-ace1-40f3-aa8b-dd64c720d18b.png)

`Neuron` should be launched when the `ckb node` outside is running, then `neuron` will fetch data from the outside one instead of the inside one. (And since we didn't find the error of `ckb node` inside `neuron`, we have to run the outside one whenever we want to use neuron)

When `neuron` is open, it will connect to the `ckb node` outside and start synchronize with it. Once `neuron` reaches the latest block, you can switch to the `nervos dao` tab and follow this [doc](https://docs.nervos.org/docs/basics/guides/crypto%20wallets/neuron/#withdraw-ckb-from-nervos-dao) to withdraw assets.

**Comment by Mrschengen** [comment]
really its hard to understand how this can work; i closed ckb inside node , then when i lunche it back i saw blocks start downloading from zero again, and in ckb node this error ! 
 

![ckbinside node](https://user-images.githubusercontent.com/109836736/183474119-f357af06-1567-418b-ab18-67fad2f7292c.png)

**Comment by Mrschengen** [comment]
i lunched Neuron after syncing was completed ! and i get this error 

![ckb node inside](https://user-images.githubusercontent.com/109836736/183474740-e2e3cac9-cdc7-44f8-8aaa-639deaf10bb2.png)

**Comment by Mrschengen** [comment]
Thats enough for me ! this get blocked again here as you see in the picture . for the last time i will ask this please no other why to acces to my funds ? its enough for me i dont have more patient to wait more and get always get stacked.
Hope if thers other solution away from waiting blocks or doing anything related to this 
![blockedagain](https://user-images.githubusercontent.com/109836736/184059366-f2259645-6210-40ee-8e97-b8e1e58b1f49.png)

**Comment by Keith-CY** [comment]
> Thats enough for me ! this get blocked again here as you see in the picture . for the last time i will ask this please no other why to acces to my funds ? its enough for me i dont have more patient to wait more and get always get stacked. Hope if thers other solution away from waiting blocks or doing anything related to this ![blockedagain](https://user-images.githubusercontent.com/109836736/184059366-f2259645-6210-40ee-8e97-b8e1e58b1f49.png)

Sorry for that I missed the last comment 2 days ago

For this message
```
i lunched Neuron after syncing on node inside was completed ! and i get this error and the neuron keep blocked also , so if i close the neuron then the CKB node insid back to work as normal again !
```

Are you meaning `after syncing no node outside was completed` and the log is printed by the `ckb node` outside the neuron

I didn't see this error message before and looked for help from the core team

**Comment by Keith-CY** [comment]
And please upload `neuron`'s logs again so I can check why neuron hangs with the `ckb node` outside

**Comment by Mrschengen** [comment]
[main.log](https://github.com/nervosnetwork/neuron/files/9305906/main.log)

**Comment by Mrschengen** [comment]
But to be honest am not looking for the problem any more , its enough for me . please ask the team if thers other way to get the fund out, i start even thinking to left all even the fund if thers no way to acces to them ....

**Comment by Keith-CY** [comment]
Neuron's log shows that connection to `ckb node` is lost

```
[2022-08-11 04:03:51.660] [info] Database:	saved synced block #2174900
[2022-08-11 04:14:57.868] [warn] function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
[2022-08-11 04:14:57.973] [warn] function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
```

And we got a potential reason about why `ckb node` is not working. It's too technical about for me so core team will reply in this issue

**Comment by quake** [comment]
> i lunched Neuron after syncing on node inside was completed ! and i get this error and the neuron keep blocked also , so if i close the neuron then the CKB node insid back to work as normal again !
> 
> ![ckb node inside](https://user-images.githubusercontent.com/109836736/183474740-e2e3cac9-cdc7-44f8-8aaa-639deaf10bb2.png)

This error appears to be caused by a hard drive read/write error, can you try checking with windows disk utility to see if there are any errors?

**Comment by Mrschengen** [comment]
> ors?

this is already solved when i get it i just need to close all, and start all from zero, but the real problem is that always the Neuron get blocked and each time in different block .

**Comment by Mrschengen** [comment]
> Neuron's log shows that connection to `ckb node` was lost
> 
> ```
> [2022-08-11 04:03:51.660] [info] Database:	saved synced block #2174900
> [2022-08-11 04:14:57.868] [warn] function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 2 ...
> [2022-08-11 04:14:57.973] [warn] function call error: Error: connect ECONNREFUSED 127.0.0.1:8114, retry 3 ...
> ```
> 
> And we get a potential reason about why `ckb node` is not working. It's too technical to me so core team will reply in this issue

if this always happen! we lost connection to ckb node ! we need to find away to get back the conection ! and please dont tell me we need to delet cash and do full rebuild ! because i dont have more patient to do that. please i need to get out my funds without this ! its enough for me

**Comment by Keith-CY** [comment]
> > ors?
> 
> this is already solved when i get it i just need to close all, and start all from zero, but the real problem is that always the Neuron get blocked and each time in different block .

So now the `ckb node` outside has synced fully but neuron doesn't catch up, am I right?

From logs of `neuron`, `neuron` did't connect to a `ckb node` outside. Please shut neuron down, lauch ckb node manually and reopen neuron.

If it still not works for about 10 mins, please join discord https://discord.gg/N9nZ3JE2Gg and past the issue link, I'll create a private channel for instant communication

**Comment by Mrschengen** [comment]
> https://discord.gg/N9nZ3JE2Gg

i did this already a lot of time ! am going to discord

**Comment by Keith-CY** [comment]
> > [discord.gg/N9nZ3JE2Gg](https://discord.gg/N9nZ3JE2Gg)
> 
> i did this already a lot of time ! am going to discord

I've invited you into the private channel

**Comment by Mrschengen** [comment]
Thanks a lot for the Help, i used another laptop and i get  neuron synced at the end. maybe thers an issue with my personal laptop
