### ISSUE TITLE
[Synchronization] Stuck at "connecting" when I restart the app

### ISSUE THREAD

**Issue by Drazzerss** [nervosnetwork/neuron#2699]
### Detail of the issue

Hello guys,

So the first time i installed the wallet it worked perfectly but whenever i try to restart it i get stuck at "connnecting".
I already checked the other post about the subject and tried many suggestions but it doesnt work.
In task manager i have ckb running using 25-30%  of CPU like it's downloading or something like that.
Thank for your help guys !

-
[neuron_debug_1685999757873.zip](https://github.com/nervosnetwork/neuron/files/11657839/neuron_debug_1685999757873.zip)

**Comment by Drazzerss** [comment]
[main.log](https://github.com/nervosnetwork/neuron/files/11657893/main.log)

**Comment by Drazzerss** [comment]
THANK YOU ! 
I tested so much thing and this one worked perfectly i will just do it everytime it doesn't work and it looks to fix the problem everytime now.

Thanks to the community !

**Comment by 0xfather** [comment]
> ./data/network/peer_store/addr_manager.db
What file is this? After deleting it, it can be synchronized normally, and it seems that it will no longer be automatically generated. Is it necessary for this file to exist? If not, can the file be directly not generated or detected and automatically deleted when Neuron starts

**Comment by yanguoyu** [comment]
> > ./data/network/peer_store/addr_manager.db
> > What file is this? After deleting it, it can be synchronized normally, and it seems that it will no longer be automatically generated. Is it necessary for this file to exist? If not, can the file be directly not generated or detected and automatically deleted when Neuron starts

It caches ckb peer nodes' information. After we delete it, it will retrieve and cache. Currently, it cost unexpectedly much time to load `addr_manager.db`, so we delete it before starting ckb to temporarily avoidance of this issue. it has been fixed by https://github.com/nervosnetwork/ckb/pull/4000. So after we update the ckb version next time, we will not encounter this problem.

**Comment by sampro2001** [comment]
Hi guys there IS one mont im trying to have neuron wallah but no way and i wrote ti help and export m'y débug informations they Sand me to do thing but i still cant because i cant im not so good in this

**Comment by sampro2001** [comment]
I dont knothow to find .data_network/_peer_store  if someone Can help

**Comment by Orionstell** [comment]
> 
- go to Help: Wallet, Edit , Tools , windows, help,  at the top of your wallet, 
- click the help drop-down menu, you will see the setting section, 
- click on setting, 
- then you have a window that opens with this written: General , Wallets, Network , data, 
- click on DATA, and there you see two options, CKB node config & storage and you can see where your info is written like this C:/users/ect.... and look carefully there is a small folder icon at the end of this line,
-  click on it , click on the small folder icon. You have Data , and below 3 files you see. 
- Click on DATA, then you will see the Network folder,
-  click on the network folder, and then you will see the peer-store folder,
-  click on the peer-store folder, then you go to backup and you will find the deleted file, if you do not see the backup folder you should see the addr_manager.db file.
-  I don't know if this will help you but this is step by step, what I did.

**Comment by Orionstell** [comment]
![da](https://github.com/nervosnetwork/neuron/assets/140056079/fb31f041-5fc5-40e1-9a2a-70975bff0308)

**Comment by sampro2001** [comment]
Tanx 
Envoyé depuis Yahoo Mail pour Android 
 
  Le jeu., juil. 20, 2023 à 17:23, ***@***.***> a écrit:

**Comment by sampro2001** [comment]
I did everything they asked me but i still Can t arrive in 2% and it start to count down7
Its about 47days i speny all m'y days on it and cant get this xallet

**Comment by sampro2001** [comment]
Can someone help me

**Comment by 0xfather** [comment]
> I did everything they asked me but i still Can t arrive in 2% and it start to count down7 Its about 47days i speny all m'y days on it and cant get this xallet

1. Open the "Settings" - "Data" section of the Neuron wallet and view the directory address of the CKB node data folder (remember this address)
2. Close Neuron
3. Open the data folder address you just found and delete it with ./data/network/peer_store/addr_manager.db file
4. Reopening Neuron should enable normal synchronization

If you find that synchronization cannot be done in the future, please follow the steps above to delete addr_manager.db file and Restart Neuron

But sometimes when the synchronization is completed and the balance is found to be incorrect, it is necessary to "clear the cache" - "rebuild the index" in "Settings"

**Comment by sampro2001** [comment]
I do liké 3  Times its drill no synchronizing i Can send toi foto

Envoyé depuis Yahoo Mail pour Android 
 
  Le mer., juil. 26, 2023 à 3:08, ***@***.***> a écrit:   



I did everything they asked me but i still Can t arrive in 2% and it start to count down7 Its about 47days i speny all m'y days on it and cant get this xallet

   
   - Open the "Settings" - "Data" section of the Neuron wallet and view the directory address of the CKB node data folder (remember this address)
   - Close Neuron
   - Open the data folder address you just found and delete it with ./data/network/peer_store/addr_manager.db file
   - Reopening Neuron should enable normal synchronization

If you find that synchronization cannot be done in the future, please follow the steps above to delete addr_manager.db file and Restart Neuron

But sometimes when the synchronization is completed and the balance is found to be incorrect, it is necessary to "clear the cache" - "rebuild the index" in "Settings"

**Comment by sampro2001** [comment]
Thé light client testent synchronize very easy

Envoyé depuis Yahoo Mail pour Android 
 
  Le mer., juil. 26, 2023 à 3:08, ***@***.***> a écrit:   



I did everything they asked me but i still Can t arrive in 2% and it start to count down7 Its about 47days i speny all m'y days on it and cant get this xallet

   
   - Open the "Settings" - "Data" section of the Neuron wallet and view the directory address of the CKB node data folder (remember this address)
   - Close Neuron
   - Open the data folder address you just found and delete it with ./data/network/peer_store/addr_manager.db file
   - Reopening Neuron should enable normal synchronization

If you find that synchronization cannot be done in the future, please follow the steps above to delete addr_manager.db file and Restart Neuron

But sometimes when the synchronization is completed and the balance is found to be incorrect, it is necessary to "clear the cache" - "rebuild the index" in "Settings"

**Comment by sampro2001** [comment]
Now its synchronizing but its frol 92%going down to 00

Envoyé depuis Yahoo Mail pour Android 
 
  Le mer., juil. 26, 2023 à 3:08, ***@***.***> a écrit:   



I did everything they asked me but i still Can t arrive in 2% and it start to count down7 Its about 47days i speny all m'y days on it and cant get this xallet

   
   - Open the "Settings" - "Data" section of the Neuron wallet and view the directory address of the CKB node data folder (remember this address)
   - Close Neuron
   - Open the data folder address you just found and delete it with ./data/network/peer_store/addr_manager.db file
   - Reopening Neuron should enable normal synchronization

If you find that synchronization cannot be done in the future, please follow the steps above to delete addr_manager.db file and Restart Neuron

But sometimes when the synchronization is completed and the balance is found to be incorrect, it is necessary to "clear the cache" - "rebuild the index" in "Settings"

**Comment by yanguoyu** [comment]
@sampro2001 
> Now its synchronizing but its frol 92%going down to 00

Could you upload the debug information again when it from 92%going down to 00?

**Comment by sampro2001** [comment]
Envoyé depuis Yahoo Mail pour Android 
 
  Le ven., juil. 28, 2023 à 13:04, Cheikhou Oumar ***@***.***> a écrit:    
     Le mercredi 26 juillet 2023 à 03:08:28 UTC+2, 0xfather.com ***@***.***> a écrit :  
 
 



I did everything they asked me but i still Can t arrive in 2% and it start to count down7 Its about 47days i speny all m'y days on it and cant get this xallet

   
   - Open the "Settings" - "Data" section of the Neuron wallet and view the directory address of the CKB node data folder (remember this address)
   - Close Neuron
   - Open the data folder address you just found and delete it with ./data/network/peer_store/addr_manager.db file
   - Reopening Neuron should enable normal synchronization

If you find that synchronization cannot be done in the future, please follow the steps above to delete addr_manager.db file and Restart Neuron

But sometimes when the synchronization is completed and the balance is found to be incorrect, it is necessary to "clear the cache" - "rebuild the index" in "Settings"
